name: battleships
description: A logic puzzle inspired by the classic guessing game everyone probably played during their childhood.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  go_router: ^8.0.5
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.5
  commitlint_cli: ^0.4.1
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  go_router_builder: ^2.1.1
  husky: ^0.1.6
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
