name: battleships
description: A logic puzzle inspired by the classic guessing game everyone probably played during their childhood.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  commitlint_cli: ^0.4.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  husky: ^0.1.6

flutter:
  uses-material-design: true
